### ISSUE TITLE
Confused about sending info back to client

### ISSUE THREAD

**Issue by dspencer926** [dspencer926/speakeasy#4]
Hey y'alllll

Since the Google API fetch has to be done from the backend, I've got the front end sending a POST (with two strings: [text to be translated], [and target language to translate into] to the backend, who then takes that info and does another fetch to the API.  I can then get the translated results to console log on the backend log (in terminal) but am a little confused about how to send it back to the frontend.  

I put the Google fetch in another function (trying to use the same format as when we've made the db call in the model, but i don't know how to get it to return the translated string to the original controller function so that I can send it back as a res to the frontend.  Any suggestions?

@thoughtbyte
@jlr7245
@shishkina
@zfine416

**Comment by jlr7245** [comment]
Sure thing. Check out [this section](https://git.generalassemb.ly/nyc-wdi-ada/MINI_LECTURE-APIS-from-the-backend#reslocals) of the calls-from-the-backend mini lecture, I think it will answer your question :)

**Comment by dspencer926** [comment]
Thx

**Comment by dspencer926** [comment]
It's not working for some reason... when it goes back to the controller from the helper route, the res is empty... :(

actually no, the res isn't empty, just the "locals" property 

@thoughtbyte
@jlr7245
@shishkina
@zfine416

**Comment by dspencer926** [comment]
Okay nevermind i think i got it ahhh i'm a dummy

**Comment by jlr7245** [comment]
it might also help if you didn't try to send back tweeds in some of your phrase controllers  ;)

**Comment by dspencer926** [comment]
oh haha I fixed that I just haven't committed since I fixed it ...

but so I thought i had it... meaning I figured out why the res.locals weren't coming through to the controller.... but now my problem is i have the information in the controller but i still don't know how to send it back to the front end... in the example you render it as a view, but we're not doing that anymore... so I  do:

   res.json({message: 'worked'})

and that gives me an object that I can console log in the front end... and when I comment that line out, I don't get a response in the front end (nothing displays in the console long)... so I know it's doing something... but the data that I'm trying to pass in that object (the string 'worked')  doesn't show up in the object.  I just has regular generic data:

Response {type: "cors", url: "http://localhost:3001/translation", redirected: false, status: 200, ok: true…}
body
:
(...)
bodyUsed
:
false
headers
:
Headers
ok
:
true
redirected
:
false
status
:
200
statusText
:
"OK"
type
:
"cors"
url
:
"http://localhost:3001/translation"
__proto__
:
Response

Any other ideas? :)

@thoughtbyte
@jlr7245
@shishkina
@zfine416

**Comment by jlr7245** [comment]
did you remember to do `res.json()`?

**Comment by dspencer926** [comment]
ahhhhhhhhhhhHHHHHhh IT WORKS THANK YOU!!!!!!!   XD
